name: 'ktfmt-action'
description: 'Github action for ktfmt'
author: 'Rashad Sookram'
inputs:
  style:
    required: false
    description: 'The style the code should be formatted as (dropbox, google, or kotlinlang). Defaults to facebook style.'
runs:
  using: 'node12'
  main: 'dist/index.js'
